Updated Clean Architecture template to make it more similar to `scala-seed.g8`
DevInsideYou/cat.g8 pull request #1
Opened 2022-02-03 21:21 UTC by ZheniaTrochun

2022-02-03 21:48 UTC, agilesteel requested changes
Thank you for this! Please make sure that the project generated by this is well formatted. You can do this by making sure that `sbt styleCheck` does not bark at you. Also make sure that there are no warnings.

This will help you with the diffs:
```bash
git init
git add .
git commit -m "Initial commit"
sbt styleFix
git diff
```

2022-02-03 21:48 UTC, agilesteel commented on src/main/g8/build.sbt
>  lazy val oneToOneClasspathDependencies: String =
If you `import Util._` it has `Cctt` which does the same thing so you can throw this one out.

2022-02-03 21:48 UTC, agilesteel commented on src/main/g8/project/plugins.sbt
> +addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.13.1")
Please add an empty line.

2022-02-03 21:48 UTC, agilesteel commented on src/main/g8/.scalafix.conf
> +rules = [
This is not the latest version. It causes issues. Please download the new file.

2022-02-03 21:48 UTC, agilesteel commented on src/main/g8/.scalafmt.conf
> +version = "3.4.0"
This is not the latest version. It causes issues. Please download the new file.

2022-02-04 13:59 UTC, ZheniaTrochun commented
Thank you for your comments!
I've fixed formatting and made requested changes.
Also the style check passes without any problems in a newly generated project.

2022-02-04 15:34 UTC, agilesteel requested changes
Awesome, I just noticed one last thing: the directories under `.g8/uescase` need to be renamed (they need the numberes).

```
core -> 02-core
delivery -> 03-delivery
persistence -> 03-persistence
main -> 04-main
```
I think it's the last thing left to do it. I'll merge it afterward. Thanks again for doing this!

2022-02-04 16:12 UTC, ZheniaTrochun commented
Good catch! I've renamed those folders too.

2022-02-04 16:19 UTC, agilesteel commented
Awesome!

2022-02-04 16:19 UTC, merged